### ISSUE TITLE
undefined method `refresh_line'

### ISSUE THREAD

**Issue by Spectrum735** [animotto/sandbox-ruby#4]
hi animotto!
Ho to fix an error when i try to run any script. 

```✿ Run: simlink [4]
✿ Error: simlink [4]

4. C:/ta-hackers/ta-hackers-2.0/lib/cli/context/script.rb:79:in `block (2 levels) in <top (required)>'
3. C:/ta-hackers/ta-hackers-2.0/lib/cli/context/script.rb:40:in `script_run'
2. C:/ta-hackers/ta-hackers-2.0/lib/cli/sandbox.rb:45:in `log'
1. C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sandbox-ruby-0.1/lib/sandbox/shell.rb:109:in `puts'

=> undefined method `refresh_line' for Reline:Module
#<Thread:0x00000220666ec7a0 C:/ta-hackers/ta-hackers-2.0/lib/cli/context/script.rb:79 run> terminated with exception (report_on_exception is true):
/script ▸ C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sandbox-ruby-0.1/lib/sandbox/shell.rb:109:in `puts': undefined method `refresh_line' for Reline:Module (NoMethodError)

      Readline.refresh_line if @reading
              ^^^^^^^^^^^^^
        from C:/ta-hackers/ta-hackers-2.0/lib/cli/sandbox.rb:49:in `error'
        from C:/ta-hackers/ta-hackers-2.0/lib/cli/context/script.rb:60:in `script_log_backtrace'
        from C:/ta-hackers/ta-hackers-2.0/lib/cli/context/script.rb:45:in `rescue in script_run'
        from C:/ta-hackers/ta-hackers-2.0/lib/cli/context/script.rb:34:in `script_run'
        from C:/ta-hackers/ta-hackers-2.0/lib/cli/context/script.rb:79:in `block (2 levels) in <top (required)>'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sandbox-ruby-0.1/lib/sandbox/shell.rb:109:in `puts': undefined method `refresh_line' for Reline:Module (NoMethodError)

      Readline.refresh_line if @reading
              ^^^^^^^^^^^^^
        from C:/ta-hackers/ta-hackers-2.0/lib/cli/sandbox.rb:45:in `log'
        from C:/ta-hackers/ta-hackers-2.0/lib/cli/context/script.rb:40:in `script_run'
        from C:/ta-hackers/ta-hackers-2.0/lib/cli/context/script.rb:79:in `block (2 levels) in <top (required)>'```

**Comment by Spectrum735** [comment]
To fixed this need to comment or remove 109 line in C:\Ruby<ver>\lib\ruby\gems\3.2.0\gems\sandbox-ruby-0.1\lib\sandbox\shell.rb
